jackfirth/resyntax

- cli.rkt
- code-snippet.rkt
> Fix snippet indentation

- refactoring-rule.rkt
> Add some rules for refactoring for loops

- cli.rkt
- info.rkt
- main.rkt
- string-replacement.rkt
Part of #36. It's got some issues but it's a start.
> Add a basic CLI for fixing code.

- .github/workflows/main.yml
- cli.rkt
- info.rkt
- let-to-define-test.rkt
- main.rkt
- source-code.rkt
- string-replacement.rkt
- testing/refactoring-test-parser.rkt
- testing/refactoring-test-tokenizer.rkt
- testing/refactoring-test.rkt
> Add a #lang for testing refactoring rules

- default-recommendations/legacy-contract-migrations.rkt
> Get rid of the flat-contract-predicate migration

- cli.rkt
This makes it easier to see what the most frequently occurring problems are.
> Sort rule fix counts in CLI output

- default-recommendations/for-loop-shortcuts-test.rkt
- default-recommendations/for-loop-shortcuts.rkt
- default-recommendations/let-binding-suggestions-comment-test.rkt
- default-recommendations/let-binding-suggestions-function-shortcuts-test.rkt
- default-recommendations/let-binding-suggestions-test.rkt
- default-recommendations/let-binding-suggestions.rkt
- default-recommendations/private/let-binding.rkt
- default-recommendations/private/syntax-identifier-sets.rkt
- syntax-replacement.rkt
Kind of a grab bag of changes here. See commit messages for details.
> Rework various things

- default-recommendations/function-definition-shortcuts-test.rkt
- default-recommendations/function-definition-shortcuts.rkt
- default-recommendations/private/syntax-lines.rkt
> Avoid migrating some functions with multiline headers to curried form

- default-recommendations.rkt
- default-recommendations/comparison-shortcuts-test.rkt
- default-recommendations/comparison-shortcuts.rkt
Saw this in some student homework code.
> Add comparison shortcuts

- testing/refactoring-test.rkt
> Improve test failure messages

- default-recommendations/let-binding-suggestions-test.rkt
- testing/refactoring-test.rkt
> Check that the output of a refactored program doesn't change

- default-recommendations.rkt
- default-recommendations/contract-shortcuts-test.rkt
- default-recommendations/contract-shortcuts.rkt
> Add some contract shortcuts

- default-recommendations/let-binding-suggestions-test.rkt
- default-recommendations/let-binding-suggestions.rkt
- default-recommendations/private/let-binding.rkt
> Implement support for eliminating let*-values forms

- string-replacement.rkt
> Rename some string replacement functions

- default-recommendations/boolean-shortcuts-test.rkt
- default-recommendations/comparison-shortcuts-test.rkt
- default-recommendations/conditional-shortcuts-test.rkt
- default-recommendations/contract-shortcuts-test.rkt
- default-recommendations/for-loop-shortcuts-test.rkt
- default-recommendations/function-definition-shortcuts-test.rkt
- default-recommendations/hash-shortcuts-test.rkt
- default-recommendations/legacy-struct-migrations-test.rkt
- default-recommendations/let-binding-suggestions-comment-test.rkt
- default-recommendations/let-binding-suggestions-function-shortcuts-test.rkt
- default-recommendations/let-binding-suggestions-test.rkt
- testing/refactoring-test-parser.rkt
- testing/refactoring-test-tokenizer.rkt
- testing/refactoring-test.rkt
> Let test files specify a shared header for test programs

- default-recommendations/let-binding-suggestions-comment-test.rkt
- main.rkt
- private/comment-reader.rkt
- private/syntax-traversal.rkt
- syntax-replacement.rkt
A little light on tests but oh well. Closes #5.
> Don't apply changes when they drop comments

- default-recommendations/list-shortcuts-test.rkt
- default-recommendations/list-shortcuts.rkt
Also, tidy up the list shortcuts test. Closes #104.
> Add rule for append calls that do nothing

- default-recommendations.rkt
- default-recommendations/syntax-rules-shortcuts-test.rkt
- default-recommendations/syntax-rules-shortcuts.rkt
> Add shortcuts for syntax-rules

- default-recommendations.rkt
- default-recommendations/numeric-shortcuts-test.rkt
- default-recommendations/numeric-shortcuts.rkt
> Add shortcuts for lambdas equivalent to add1 and sub1

- default-recommendations/numeric-shortcuts-test.rkt
- default-recommendations/numeric-shortcuts.rkt
> Suggest positive? and negative? instead of equivalent lambdas

- default-recommendations/conditional-shortcuts-test.rkt
- default-recommendations/legacy-struct-migrations-test.rkt
- default-recommendations/list-shortcuts-test.rkt
- default-recommendations/numeric-shortcuts-test.rkt
Single-line code blocks and multiple inputs per test allow these test cases to be simplified a little.
> Simplify tests using newer testing language features

- default-recommendations.rkt
Will turn this back on when #47 is resolved.
> Disable `legacy-struct-migrations`

- default-recommendations/numeric-shortcuts-test.rkt
- default-recommendations/numeric-shortcuts.rkt
> A couple of basic identity rewrites.

- default-recommendations/boolean-shortcuts-test.rkt
- default-recommendations/boolean-shortcuts.rkt
- default-recommendations/private/boolean.rkt
Closes #139. Also includes some useful utilities for detecting when expressions probably evaluate to a boolean.
> Add more boolean shortcuts

- default-recommendations.rkt
- default-recommendations/legacy-syntax-migrations-test.rkt
- default-recommendations/legacy-syntax-migrations.rkt
> Add some migrations for legacy syntax functions

- cli.rkt
- file-group.rkt
- info.rkt
- main.scrbl
- private/github.rkt
- private/run-command.rkt
- private/string-indent.rkt
This code is rather messy, but [it does work](https://github.com/jackfirth/racket-package-resyntax-action/pull/9). And it gives any user who can install Racket packages in a GitHub action the ability to review GitHub pull requests with Resyntax.
> Add GitHub integration

- default-recommendations/let-binding-suggestions.rkt
- default-recommendations/private/let-binding.rkt
- main.rkt
- private/source.rkt
- refactoring-rule.rkt
> Change how expansion analysis is passed to rules

- default-recommendations.rkt
- default-recommendations/syntax-shortcuts-test.rkt
- default-recommendations/syntax-shortcuts.rkt
> Add `format-id` `syntax-e` shortcut

- default-recommendations/conditional-shortcuts-test.rkt
- default-recommendations/conditional-shortcuts.rkt
Also, rename the rule to `cond-let-to-cond-define`.
> Fix a bug in `cond-let-to-cond-define`

- README.md
probably need to add this to the manual
> install guidance

- default-recommendations/list-shortcuts-test.rkt
- default-recommendations/list-shortcuts.rkt
Closes #181. These aren't particularly valuable and aren't worth the noise.
> Remove empty list canonicalization suggestions

- default-recommendations/conditional-shortcuts-test.rkt
- default-recommendations/conditional-shortcuts.rkt
- default-recommendations/private/let-binding.rkt
- default-recommendations/private/syntax-lines.rkt
> Suggest `cond` instead of `if` when appropriate.

- main.rkt
- private/refactoring-result.rkt
- private/string-replacement.rkt
- private/syntax-range.rkt
> Don't generate overlapping suggestions

- default-recommendations.rkt
- default-recommendations/string-shortcuts-test.rkt
- default-recommendations/string-shortcuts.rkt
> Suggest `(newline)` when appropriate.

- default-recommendations/contract-shortcuts-test.rkt
- default-recommendations/contract-shortcuts.rkt
> Suggest using `path-string?` when appropriate

- default-recommendations/legacy-syntax-migrations-test.rkt
- default-recommendations/legacy-syntax-migrations.rkt
> Migrate away from legacy `syntax-local-introduce` variants

- default-recommendations/string-shortcuts-test.rkt
- default-recommendations/string-shortcuts.rkt
> Suggest using `string-join` keyword arguments

- default-recommendations/string-shortcuts-test.rkt
- default-recommendations/string-shortcuts.rkt
> Add some string identity rewrites

- default-recommendations/contract-shortcuts-test.rkt
- default-recommendations/contract-shortcuts.rkt
> Suggest using `->` with ellipses when appropriate

- default-recommendations/boolean-shortcuts-test.rkt
- default-recommendations/boolean-shortcuts.rkt
> Remove De Morgan suggestions

- default-recommendations/list-shortcuts-test.rkt
- default-recommendations/list-shortcuts.rkt
> Recommend `list` instead of unnecessary quotation

- default-recommendations.rkt
- default-recommendations/function-shortcuts-test.rkt
- default-recommendations/function-shortcuts.rkt
> Simplify `apply` expressions

- default-recommendations.rkt
- default-recommendations/definition-shortcuts-test.rkt
- default-recommendations/definition-shortcuts.rkt
- default-recommendations/private/definition-context.rkt
> Suggest splitting `define-values` when appropriate

- default-recommendations/for-loop-shortcuts-test.rkt
- default-recommendations/for-loop-shortcuts.rkt
> Add a shortcut for `(apply append ...)` on a loop

- default-recommendations/for-loop-shortcuts-test.rkt
- default-recommendations/for-loop-shortcuts.rkt
> Rewrite `list->set` on a for loop to `for/set`

- cli.rkt
I'm planning on using this in the [autofixer workflow](https://github.com/racket/drracket/blob/03c5a125a02ed37af13c43dc297737ed2a9647a3/.github/workflows/resyntax-autofixer.yml) I added to the [racket/drracket](https://github.com/racket/drracket) repository.
> Add an option to limit how many fixes are applied

- default-recommendations/list-shortcuts-test.rkt
- default-recommendations/list-shortcuts.rkt
Saw this case in some old code.
> Add some shortcuts for `remove*` and friends

- default-recommendations/function-definition-shortcuts-test.rkt
- default-recommendations/function-definition-shortcuts.rkt
> Fix `define-case-lambda-to-define` size issue

- main.scrbl
- private/file-group.rkt
> Allow running Resyntax on `#lang racket` files.

- default-recommendations/for-loop-shortcuts-test.rkt
- default-recommendations/for-loop-shortcuts.rkt
This is similar to `for-each-to-for` but for refactoring `map` into `for/list`.
Closes #193 and #245.
> Add `map-to-for` refactoring

- main.rkt
Also, improve the error message formatting.
> Use logger for expansion failures

- default-recommendations/function-shortcuts-test.rkt
- default-recommendations/function-shortcuts.rkt
Saw this in some Scribble code today.
> Add a rule for single-case `case-lambda`

- default-recommendations/list-shortcuts-test.rkt
- default-recommendations/list-shortcuts.rkt
> Add `ignored-map-to-for-each`

- default-recommendations/definition-shortcuts-test.rkt
- default-recommendations/definition-shortcuts.rkt
> Add `inline-unnecessary-define` rule

- default-recommendations/contract-shortcuts-test.rkt
- default-recommendations/contract-shortcuts.rkt
> Add `provide/contract-to-contract-out` rule

- default-recommendations.rkt
- default-recommendations/file-io-suggestions-test.rkt
- default-recommendations/file-io-suggestions.rkt
> Add `make-temporary-directory-migration` rule

- default-recommendations/let-binding-suggestions-test.rkt
- default-recommendations/private/let-binding.rkt
Closes #230. Also, slightly improve debug logs.
> Improve `let-to-define` self-shadowing detection

- default-recommendations/legacy-contract-migrations-test.rkt
- default-recommendations/legacy-contract-migrations.rkt
> Add `predicate/c-migration` rule

- default-recommendations/string-shortcuts-test.rkt
- default-recommendations/string-shortcuts.rkt
> Add `display-and-newline-to-displayln` rule

- default-recommendations.rkt
- default-recommendations/boolean-shortcuts.rkt
- default-recommendations/comparison-shortcuts.rkt
- default-recommendations/conditional-shortcuts.rkt
- default-recommendations/contract-shortcuts.rkt
- default-recommendations/definition-shortcuts.rkt
- default-recommendations/file-io-suggestions.rkt
- default-recommendations/for-loop-shortcuts.rkt
- default-recommendations/function-definition-shortcuts.rkt
- default-recommendations/function-shortcuts.rkt
- default-recommendations/gap-preservation.rkt
- default-recommendations/hash-shortcuts.rkt
- default-recommendations/legacy-contract-migrations.rkt
- default-recommendations/legacy-struct-migrations.rkt
- default-recommendations/legacy-syntax-migrations.rkt
- default-recommendations/let-binding-suggestions.rkt
- default-recommendations/list-shortcuts.rkt
- default-recommendations/match-shortcuts.rkt
- default-recommendations/miscellaneous-suggestions.rkt
- default-recommendations/numeric-shortcuts.rkt
- default-recommendations/require-and-provide-suggestions.rkt
- default-recommendations/string-shortcuts.rkt
- default-recommendations/syntax-parse-shortcuts.rkt
- default-recommendations/syntax-rules-shortcuts.rkt
- default-recommendations/syntax-shortcuts.rkt
- refactoring-suite.rkt
> Add `define-refactoring-suite` macro

- default-recommendations/let-binding-suggestions-nesting-test.rkt
- default-recommendations/private/let-binding.rkt
> Refactor nested let bindings in one pass

- private/file-group.rkt
> Fix error message for uninstalled packages

- main.rkt
- private/line-replacement.rkt
- private/refactoring-result.rkt
- private/source.rkt
- private/string-replacement.rkt
> Post-filter results to changed lines only

- default-recommendations/for-loop-shortcuts-test.rkt
- default-recommendations/for-loop-shortcuts.rkt
> Add nested `for/or` and `for/and` rules

- cli.rkt
> Add `--max-modified-files` flag

- default-recommendations/require-and-provide-suggestions-test.rkt
- default-recommendations/require-and-provide-suggestions.rkt
> Only tidy requires when they're fully understood

- default-recommendations/for-loop-shortcuts-test.rkt
- default-recommendations/for-loop-shortcuts.rkt
> Add `append-map-for/list-to-for*/list` rule

- default-recommendations/list-shortcuts-test.rkt
- default-recommendations/list-shortcuts.rkt
> Add `quasiquote-to-append` rule

- default-recommendations/private/definition-context.rkt
- info.rkt
> Add `defmacro` to list of definition context forms

- cli.rkt
- private/limiting.rkt
- private/refactoring-result.rkt
> Add `--max-modified-lines`

- main.scrbl
> Add more documentation

- default-recommendations/match-shortcuts-test.rkt
- default-recommendations/match-shortcuts.rkt
> Fix formatting issue in `match-define` refactoring

- default-recommendations/function-definition-shortcuts-test.rkt
- default-recommendations/function-definition-shortcuts.rkt
> Avoid curried-function definitions for thunks

- default-recommendations/syntax-parse-shortcuts-test.rkt
- default-recommendations/syntax-parse-shortcuts.rkt
As seen in jackfirth/rebellion#576.
> Fix another `define-simple-macro` formatting bug

- default-recommendations/legacy-syntax-migrations-test.rkt
- default-recommendations/legacy-syntax-migrations.rkt
> Add `for-clause-syntax-protect-migration`

- main.scrbl
Partial fix for #349. The `~focus-replacement-on` metafunction is not yet documented since it's trickier to explain.
> Document some replacement metafunctions

- default-recommendations/definition-shortcuts-test.rkt
- default-recommendations/definition-shortcuts.rkt
- default-recommendations/match-shortcuts-test.rkt
- default-recommendations/match-shortcuts.rkt
Related to jackfirth/rebellion#582.
> Improve definition context reformatting behavior

- default-recommendations/require-and-provide-suggestions-test.rkt
- default-recommendations/require-and-provide-suggestions.rkt
> Fix no-op require tidying issue

- main.scrbl
> Document definition context rule form and metafunction

- private/file-group.rkt
> Analyze 3 lines before and after modified chunks

- cli.rkt
Missed this when I implemented multipass analysis.
> Fix a bug in GitHub review integration

- default-recommendations/definition-shortcuts-test.rkt
- default-recommendations/definition-shortcuts.rkt
> Add `begin` splicing rules

- default-recommendations/definition-shortcuts-test.rkt
- default-recommendations/definition-shortcuts.rkt
> Add `begin0-begin-extraction` rule

- default-recommendations/hash-shortcuts-test.rkt
- default-recommendations/hash-shortcuts.rkt
> Improve `hash-update` refactoring

- private/file-group.rkt
See [this breakage](https://github.com/racket/typed-racket/actions/runs/12037964410/job/33863647242?pr=1414).
> Fix negative line numbers bug

- default-recommendations.rkt
Turning this off because of #410.
> Turn off unused binding suggestions

- default-recommendations/comparison-shortcuts-test.rkt
- default-recommendations/comparison-shortcuts.rkt
See [this comment](https://github.com/racket/drracket/pull/734/commits/5c7c19f6f48511d71279eaef388b365550f9b05c#r2040841364).
> Fix a bug in comparison shortcuts

- default-recommendations/for-loop-shortcuts-test.rkt
- default-recommendations/for-loop-shortcuts.rkt
> Add `hash-for-each-to-for`

- default-recommendations/miscellaneous-suggestions.rkt
> Delete buggy `or-cond-to-cond` rule

- default-recommendations/conditional-shortcuts-test.rkt
- default-recommendations/conditional-shortcuts.rkt
> Add `throw-unless-truthy-to-or` rule

- default-recommendations/conditional-shortcuts-test.rkt
- default-recommendations/conditional-shortcuts.rkt
See discussion in herbie-fp/herbie#1304.
> Improve `throw-unless-truthy-to-or` formatting

- default-recommendations/match-shortcuts-test.rkt
- default-recommendations/match-shortcuts.rkt
> Fix `single-clause-match-to-match-define` conflicts

- base.rkt
- default-recommendations/for-loop-shortcuts-test.rkt
- default-recommendations/for-loop-shortcuts.rkt
- default-recommendations/private/list-function.rkt
- private/syntax-traversal.rkt
> Rewrite named lets into `for/or` and `for/and`

- default-recommendations/list-shortcuts-test.rkt
- default-recommendations/list-shortcuts.rkt
> Add `length-comparison-to-empty-check` rule

- default-recommendations/for-loop-shortcuts-test.rkt
- default-recommendations/for-loop-shortcuts.rkt
> Add `build-list-to-for` rule

- default-recommendations/list-shortcuts-test.rkt
- default-recommendations/list-shortcuts.rkt
> Don't refactor quasiquotes with only literals

- private/syntax-path.rkt
- private/syntax-property-bundle.rkt
This is intended to make whole-module analysis easier to implement.
> Add syntax property bundle API

- default-recommendations/conditional-shortcuts-test.rkt
- default-recommendations/conditional-shortcuts.rkt
- private/source.rkt
Also, fix a bug in expansion analyzer property propagation.
Closes #485.
> Add `ignored-and-to-when`

- main.rkt
- private/source.rkt
This also opens up the possibility of using different refactoring suites for different languages.
> Improve `#lang` detection

- main.rkt
- private/source.rkt
- private/syntax-property-bundle.rkt
- test.rkt
- test/private/grammar.rkt
- test/private/rackunit.rkt
Closes #550, with some minor syntax differences.
> Add `analysis-test:` to testing language

- default-recommendations/analyzers/ignored-result-values-test.rkt
- default-recommendations/analyzers/ignored-result-values.rkt
- private/source.rkt
- test/private/rackunit.rkt
Also, improve the check failure messages a bit with more info and logs.
> Test `ignored-result-values` with DSL

- private/source.rkt
Fixes [this failure](https://github.com/racket/drracket/actions/runs/16855081642/job/47746765206).
> Make language detection fallback more lenient

- private/universal-tagged-syntax.rkt
- test.rkt
> Check `'uts-content` properties

- default-recommendations/match-shortcuts-test.rkt
- default-recommendations/match-shortcuts.rkt
Fixes the issue that occurred in herbie-fp/herbie#1382.
> Fix `=>` handling in `match-conditional-to-when`
