cli.rkt

Usage example:
```shell
racket -l resyntax/cli -- --file <file-path> --directory <directory-path> --package <package-name>
```
Part of #32.

Add CLI support for analyzing specific files, directories, and packages

---

cli.rkt
default-recommendations.rkt
default-recommendations/for-loop-shortcuts.rkt
default-recommendations/legacy-contract-migrations.rkt
default-recommendations/legacy-struct-migrations.rkt
default-recommendations/let-binding-suggestions.rkt
default-recommendations/miscellaneous-suggestions.rkt
main.rkt
refactoring-suite.rkt
testing/refactoring-test.rkt

To represent groups of rules, this change defines a "refactoring suite" type that's just a simple named wrapper around a list of rules. Closes #53.

Add support for specifying what rules to run using the CLI

---

default-recommendations.rkt
default-recommendations/for-loop-shortcuts-test.rkt
default-recommendations/function-definition-shortcuts-test.rkt
default-recommendations/function-definition-shortcuts.rkt
default-recommendations/legacy-struct-migrations-test.rkt
default-recommendations/let-binding-suggestions-comment-test.rkt
default-recommendations/let-binding-suggestions-function-shortcuts-test.rkt
default-recommendations/let-binding-suggestions-test.rkt
default-recommendations/miscellaneous-suggestions.rkt
syntax-replacement.rkt

Additionally:
- Add more tests.
- Implement better whitespace inference between subforms when rendering syntax replacement templates.
- Reprovide refactoring suites from `resyntax/default-recommendations` to make them easier to import in the CLI and tests.

Split function definition shortcuts into separate suite

---

default-recommendations/let-binding-suggestions-test.rkt
default-recommendations/let-binding-suggestions.rkt
default-recommendations/private/let-binding.rkt

Only make suggestions when let forms can be fully migrated, and stop suggesting changing code to use `cond` to simplify let forms. In fact, stop making suggestions about `cond` altogether, since the current rules for `cond` aren't good enough at preserving comments and minimizing the number of passes.
This change also fixes a bug where let expressions in `when`, `unless`, `with-handlers`, and `parameterize` forms weren't migrated.
Closes #58.

Cut back on let binding suggestions.

---

default-recommendations.rkt
default-recommendations/boolean-shortcuts-test.rkt
default-recommendations/boolean-shortcuts.rkt
default-recommendations/miscellaneous-suggestions.rkt
default-recommendations/private/syntax-tree.rkt

These rules already existed in the `miscellaneous-suggestions` suite, but they weren't very robust. This makes them slightly more robust and easier to generalize.

Add boolean shortcuts for flattening nested ors and ands

---

default-recommendations/list-shortcuts-test.rkt
default-recommendations/list-shortcuts.rkt

Adds a new refactoring rule named `list-call-to-empty-list-literal` which refactors calls to `(list)` with no arguments to the empty list literal `'()`.

Refactor (list) to '()

---

main.rkt
testing/refactoring-test.rkt

Also, include the original code, the actual code, and the expected code in test failure messages where incorrect changes were made. Closes #80.

Include matched rule names in test failures

---

default-recommendations.rkt
default-recommendations/conditional-suggestions-test.rkt
default-recommendations/conditional-suggestions.rkt
default-recommendations/miscellaneous-suggestions.rkt

Refactor deeply-nested `(if cond then (if cond then ...))` chains into `(cond)` forms.

Add nested-if-to-cond rule

---

default-recommendations/boolean-shortcuts-test.rkt
default-recommendations/comparison-shortcuts-test.rkt
default-recommendations/conditional-shortcuts-test.rkt
default-recommendations/contract-shortcuts-test.rkt
default-recommendations/for-loop-shortcuts-test.rkt
default-recommendations/function-definition-shortcuts-test.rkt
default-recommendations/hash-shortcuts-test.rkt
default-recommendations/legacy-struct-migrations-test.rkt
default-recommendations/let-binding-suggestions-comment-test.rkt
default-recommendations/let-binding-suggestions-function-shortcuts-test.rkt
default-recommendations/let-binding-suggestions-test.rkt
default-recommendations/list-shortcuts-test.rkt
testing/refactoring-test-parser.rkt
testing/refactoring-test-tokenizer.rkt

Closes #72. Most tests can't use it yet because #70 isn't implemented, but a few can. This also required adjusting the reader to read entire code blocks as a single token, instead of tokenizing the separator lines and lang blocks separately. This means an extra separator line is needed between two code blocks, since they need their own separate start and end separator lines and can't share a separator line boundary.

Implement one-line code block syntax for tests

---

default-recommendations/let-binding-suggestions-test.rkt
default-recommendations/let-binding-suggestions.rkt
default-recommendations/private/syntax-equivalence.rkt

Encountered [here](https://github.com/soegaard/little-helper/blob/26249c688e5adf1e2535c405c6289030eff561b4/lexer.rkt#L61).

Add a shortcut for using call-with-values instead of let-values

---

cli.rkt

[Typo] Put the "anal" in "analyze"

---

.github/workflows/main.yml

Recently, tests have been failing randomly and inconsistently with GDK errors. Working theory is that xvfb-run isn't cooperating well with the way `raco test --drdr` runs each test in a separate process and runs multiple tests in parallel. This change removes the `--drdr` mode. Note that `--package` still causes each test to run in a separate process, but (to my knowledge) does _not_ cause tests to run in parallel. So hopefully this removes the flakiness.

Try to deflake CI

---

default-recommendations/syntax-parse-shortcuts-test.rkt
default-recommendations/syntax-parse-shortcuts.rkt
testing/refactoring-test.rkt

Fixes #106. Also, this improves the testing infrastructure to tell the difference between no refactoring rules matching the input and rules matching but producing no-op fixes.

Fix issue where define-syntax-parse-rule is recognized as define-simple-macro

---

default-recommendations/comparison-shortcuts-test.rkt
testing/refactoring-test-parser.rkt
testing/refactoring-test.rkt

The test checks that *each input* produces the expected output (the last code block/line is always the expected output). This makes it easier to write tests for conditionals and comparisons, since those test cases tend to have a combinatorial explosion in the number of ways that the same code can be written.

Allow specifying multiple inputs in refactoring tests

---

default-recommendations/comparison-shortcuts-test.rkt
default-recommendations/comparison-shortcuts.rkt

Suggest triple comparisons instead of `and`-ing two comparisons

---

CONTRIBUTING.md
default-recommendations/boolean-shortcuts.rkt
default-recommendations/comparison-shortcuts.rkt
default-recommendations/conditional-shortcuts.rkt
default-recommendations/contract-shortcuts.rkt
default-recommendations/for-loop-shortcuts.rkt
default-recommendations/function-definition-shortcuts.rkt
default-recommendations/hash-shortcuts.rkt
default-recommendations/legacy-contract-migrations.rkt
default-recommendations/legacy-struct-migrations.rkt
default-recommendations/legacy-syntax-migrations.rkt
default-recommendations/let-binding-suggestions.rkt
default-recommendations/list-shortcuts.rkt
default-recommendations/match-shortcuts.rkt
default-recommendations/miscellaneous-suggestions.rkt
default-recommendations/numeric-shortcuts.rkt
default-recommendations/syntax-parse-shortcuts.rkt
default-recommendations/syntax-rules-shortcuts.rkt
private/github.rkt

Also adds a `CONTRIBUTING.md` for the next time I forget the exact `raco pkg` command needed to hack on this.
Future work: hyperlinks to the docs for all those identifiers!

Convert rule descriptions to Markdown

---

.gitignore
default-recommendations/conditional-shortcuts-test.rkt
default-recommendations/let-binding-suggestions-test.rkt
default-recommendations/private/let-binding.rkt
default-recommendations/shadowed-output-test.rkt
main.rkt
private/source.rkt
private/syntax-replacement.rkt
refactoring-rule.rkt

```racket
#lang racket/base
(define (and x y) (list x y))
(define (member? e l)
(if (member e l)
#t
#f))
```
should not be refactored to `(and (member e l) #t)` because `and` is shadowed.

Don't replace syntax when output has shadowed ids

---

cli.rkt
main.rkt
private/file-group.rkt
private/git.rkt
private/linemap.rkt
private/source.rkt

GitHub pull request reviews can only leave comments on lines the pull request modified. To support that, this PR changes Resyntax's `--local-git-repository` mode to only analyze the lines that were changed in the given git ref. Other lines in modified files are ignored.

Only analyze modified lines of git refs

---

private/git.rkt

Hunk headers can sometimes include the name of the function the hunk is part of, like `@@ -29,0 +30,10 @@ foo`.

Fix git hunk header message parsing

---

main.scrbl

When `tt` is used, double-hyphens get collapsed into en-dashes, which we don’t want when typesetting flags.

Minor typesetting corrections

---

private/source.rkt

The current logic is buggy and fails for changes like [this](https://github.com/jackfirth/yaragg/pull/5). The correct behavior is for Resyntax to make sure that all of the changed lines in a suggestion are included in the set of lines changed by a pull request, rather than merely checking that these two sets intersect.

Fix a bug in diff analysis

---

default-recommendations/contract-shortcuts-test.rkt
default-recommendations/contract-shortcuts.rkt

Partially addresses #191. Can't fully resolve that issue yet since it requires Resyntax to allow rules to refactor usages of single identifiers, which doesn't currently seem to work.

Remove predicate/c

---

default-recommendations/function-definition-shortcuts-test.rkt
default-recommendations/function-definition-shortcuts.rkt

Closes #186. This won't work until https://github.com/racket/racket/pull/4620 is submitted.

Don't use `define` function shorthand in classes

---

info.rkt
private/github.rkt

This used to be used in a previous iteration of the Resyntax and GitHub integration, but it isn't used anymore. Deleting it lets us get rid of the `uri-old` dependency. Fixes #225.

Remove some dead code

---

private/syntax-replacement.rkt

This isn't necessary now that `fmt` cleans up the code Resyntax produces.

Remove more obsolete formatting markup

---

main.rkt
private/logger.rkt
testing/refactoring-test.rkt

This makes test failures caused by unexpectedly discarded suggestions much easier to diagnose. In the future I might expose a CLI switch to show these messages too, but for now just surfacing them in test failures is enough.

Add debug logs and display them in tests

---

main.rkt

This allows Resyntax to continue attempting to apply other refactoring rules when one rule breaks.

Log broken refactoring attempts

---

default-recommendations/hash-shortcuts-test.rkt
default-recommendations/hash-shortcuts.rkt
default-recommendations/string-shortcuts-test.rkt
default-recommendations/string-shortcuts.rkt

Closes #246. Unfortunately, this only fires if the surrounding module is already importing `racket/string`.

Add manual `string-join` refactoring

---

default-recommendations/conditional-shortcuts-test.rkt
default-recommendations/conditional-shortcuts.rkt

Now it can detect cases where either branch of the `if` expression always throws, instead of just cases where the true branch always throws.

Improve `always-throwing-if-to-when` rule

---

default-recommendations/conditional-shortcuts.rkt
default-recommendations/definition-shortcuts.rkt
default-recommendations/let-binding-suggestions.rkt
default-recommendations/match-shortcuts.rkt
refactoring-rule.rkt

This makes it a lot easier to write more rules that target definition contexts.

Add `define-definition-context-refactoring-rule`

---

default-recommendations/let-binding-suggestions-test.rkt
default-recommendations/let-binding-suggestions.rkt

In [this code](https://github.com/jackfirth/yaragg/blob/9d48ab7152003e39aa6c1bab11a601d3723143fa/parser-tools/yacc-to-scheme.rkt#L115-L129), there's a `let` expression immediately within a `begin0` expression to compute a variable needed for the result of the `begin0` expression. But if that `let` is lifted up into a `define`, the code becomes far more readable.

Add `begin0-let-to-define-begin0` rule

---

default-recommendations/for-loop-shortcuts-test.rkt
default-recommendations/for-loop-shortcuts.rkt
main.rkt
private/syntax-replacement.rkt

Closes #215. This rule specifically only targets the case where `for/fold` is used with `define-values` and exactly one of the result values is used. That seems like the most common and easily fixable case.
Additionally, this change improves the logging for suggestions that have binding problems. Some names are also changed to make it clearer what's going on.

Add `for/fold-result-keyword` rule.

---

default-recommendations/let-binding-suggestions-comment-test.rkt
default-recommendations/private/let-binding.rkt
private/syntax-neighbors.rkt
private/syntax-replacement.rkt

The `~splicing-replacement` metafunction is similar to `~replacement`, but for the case when a sequence of multiple forms replaces a single form. This commit uses it in `let-to-define` and related rules to preserve more comments.

Add `~splicing-replacement` metafunction

---

cli.rkt
default-recommendations/for-loop-shortcuts-test.rkt
default-recommendations/for-loop-shortcuts.rkt
private/identifier-naming.rkt
private/syntax-traversal.rkt

It can refactor this:
```scheme
(let loop ([methods-check-boxess methods-check-boxess])
(cond
[(null? methods-check-boxess) null]
[else
(cons (let loop ([methods-check-boxes (car methods-check-boxess)])
(cond
[(null? methods-check-boxes) null]
[else (cons (send (car methods-check-boxes) get-value)
(loop (cdr methods-check-boxes)))]))
(loop (cdr methods-check-boxess)))]))
```
Into this:
```scheme
(for/list ([methods-check-boxes (in-list methods-check-boxess)])
(for/list ([methods-check-box (in-list methods-check-boxes)])
(send methods-check-box get-value)))
```

Add `named-let-loop-to-for/list` rule

---

default-recommendations/conditional-shortcuts-test.rkt
default-recommendations/conditional-shortcuts.rkt
default-recommendations/function-definition-shortcuts-test.rkt
default-recommendations/function-definition-shortcuts.rkt
default-recommendations/string-shortcuts.rkt
private/syntax-neighbors.rkt
private/syntax-replacement.rkt

This change adds an `#:original-splice` option to `~replacement` and replaces `ORIGINAL-GAP` with its usage. Some `ORIGINAL-GAP` uses have no equivalent and are discarded, as preserving original gaps is no longer worth the trouble now that `fmt` handles formatting decisions. Its only use is to preserve comments, and `~replacement` and `~splicing-replacement` do that well enough.

Replace `ORIGINAL-GAP` with `#:original-splice`

---

default-recommendations/windows-newline-test.rkt
main.rkt
private/source.rkt
private/string-replacement.rkt
testing/refactoring-test.rkt

Closes #272, hopefully.
As it turns out, the current code already converts `\r\n` to `\n` _when run on a Windows machine_, as that's what the `#:mode 'text` argument to the various file-reading utilities does. The problem in #272, however, is that a non-Windows system was running Resyntax on files that originally came from a Windows system. So the `\r\n` to `\n` replacement didn't happen even though `#:mode 'text` was used. Note that `read-syntax` _always_ treats `\r\n` as `\n` regardless of whether it's run on a Windows system or not. Since Resyntax is reading and writing files for the purposes of calling `read-syntax` on their contents, this pull request changes Resyntax to always replace `\r\n` with `\n` at read time regardless of what the current system is.

Always treat `\r\n` as `\n`

---

default-recommendations.rkt
default-recommendations/require-and-provide-suggestions-test.rkt
default-recommendations/require-and-provide-suggestions.rkt

Closes #28. The implementation is pretty basic and ignores things like `(provide (for-syntax x x))` but it catches the simple case.

Add `provide-deduplication` rule

---

default-recommendations/for-loop-shortcuts-test.rkt
default-recommendations/for-loop-shortcuts.rkt
default-recommendations/function-definition-shortcuts.rkt
default-recommendations/let-binding-suggestions-test.rkt
default-recommendations/let-binding-suggestions.rkt
default-recommendations/private/let-binding.rkt
main.rkt
private/linemap.rkt
private/source.rkt
refactoring-rule.rkt

Closes #276. This allows a complete rework and immense simplification of the `let-to-define` logic. It also removes the need to pass the full source code analysis object to each refactoring rule, since all of the information produced by the analysis is now embedded in the syntax object handed to the refactoring rule.
This commit also adds some miscellaneous observability improvements, including more debug logging and better error messages.

Add full expansion scopes to visited syntax

---

default-recommendations/require-and-provide-suggestions-test.rkt
default-recommendations/require-and-provide-suggestions.rkt
testing/refactoring-test.rkt

Closes #132. The order used is the same one as `racket-mode`.
Also, improve log capturing in the test framework.

Add `tidy-require` rule

---

default-recommendations.rkt
default-recommendations/console-io-suggestions-test.rkt
default-recommendations/console-io-suggestions.rkt
default-recommendations/private/syntax-identifier-sets.rkt

Closes #211. Also, fix `in-syntax-identifiers` to skip quoted identifiers.

Add `read-line-any` rule

---

default-recommendations/syntax-parse-shortcuts-test.rkt
default-recommendations/syntax-parse-shortcuts.rkt

Format less when migrating `define-simple-macro`

---

default-recommendations/for-loop-shortcuts-test.rkt
default-recommendations/for-loop-shortcuts.rkt

Closes #357. Now it only fires if the last clause uses `let`, since that probably means the `or` is just there to get some simple cases out of the way before the main logic of the loop body.

Restrict or-in-for/and refactoring to obviously useful cases

---

default-recommendations/definition-shortcuts-test.rkt
default-recommendations/definition-shortcuts.rkt

Saw this in racket/typed-racket#1402.

Don't reformat entire context when removing `define-values`

---

GITHUB_APP_PRIVACY_POLICY.md

It's required for publishing the app on the GitHub Marketplace.

Add a privacy policy for the github app

---

default-recommendations/definition-shortcuts-test.rkt
main.rkt
test.rkt
test/private/grammar.rkt
test/private/rackunit.rkt
test/private/tokenizer.rkt

This allows controlling the set of lines analyzed by Resyntax in `#lang resyntax/test`. Closes #314.

Add `@lines` test parameter

---

cli.rkt
main.rkt
private/source.rkt
test/private/rackunit.rkt

Part of #380. Now Resyntax can analyze files after prior modifications without actually modifying the files.

Add modified sources and use them for new analysis API

---

cli.rkt
main.rkt
private/commit.rkt
private/git.rkt
private/refactoring-result.rkt

Split commits

---

default-recommendations/require-and-provide-suggestions-test.rkt
default-recommendations/require-and-provide-suggestions.rkt

Fix require tidying for sneaky imports

---

default-recommendations/definition-shortcuts-test.rkt
default-recommendations/definition-shortcuts.rkt
default-recommendations/let-binding-suggestions-test.rkt
default-recommendations/let-binding-suggestions.rkt

Closes #405. Also adds a rule for flattening `begin` when it's already inside a definition context.

Add more `begin` rules

---

default-recommendations/class-shortcuts-test.rkt
default-recommendations/class-shortcuts.rkt

Add `instantiate` shortcuts

---

default-recommendations/conditional-shortcuts-test.rkt
default-recommendations/conditional-shortcuts.rkt

Add `cond-void-to-when-or-unless`

---

private/source.rkt

This should keep it out of Autofixer pull request descriptions, as observed in racket/typed-racket#1417.

Capture printed output when analyzing code

---

default-recommendations/require-and-provide-suggestions-test.rkt
default-recommendations/require-and-provide-suggestions.rkt

It has an inconsistency with racket-mode. Disabling it until #432 is resolved.

Disable require tidying for now

---

default-recommendations/for-loop-shortcuts-test.rkt
default-recommendations/for-loop-shortcuts.rkt

See jackfirst/resyntax#435; this lint tends to produce worse output than the input it started with.

Remove the `apply-append-for-loop-to-for-loop` lint

---

default-recommendations/syntax-shortcuts-test.rkt
default-recommendations/syntax-shortcuts.rkt

See [this comment](https://github.com/racket/typed-racket/pull/1438#discussion_r1979909976).

Add `format-string-to-format-symbol` rule

---

default-recommendations/list-shortcuts-test.rkt
default-recommendations/list-shortcuts.rkt

See [this suggestion](https://github.com/racket/scribble/pull/483#discussion_r1967097346).

Add `list-selectors-to-take-and-drop`

---

default-recommendations/numeric-shortcuts-test.rkt
default-recommendations/numeric-shortcuts.rkt

Remove non-lambda `positive?` and `negative?` rules

---

private/logger.rkt

This utility makes it much easier to debug refactoring rule `#:when` conditions in tests.

Add `log-resyntax-rule-condition`

---

private/analyzer.rkt
private/fully-expanded-syntax.rkt
private/source.rkt
private/syntax-path.rkt
private/syntax-property-bundle.rkt

Supersedes #514. Currently, only a single hard-coded analyzer is used, but this system is easily extendable to multiple hard-coded analyzers. Bundling analyzers with refactoring suites in the future is also possible, with a bit more work.
There's a TODO or two left to implement in here, but I want to get this merged and functioning before dealing with them.

Add whole-module analyzer system

---

default-recommendations/let-binding-suggestions-test.rkt
default-recommendations/let-binding-suggestions.rkt

Fixes the issue observed in racket/typed-racket#1463.

Reformat single-line clauses in `let-to-define`

---

default-recommendations/boolean-shortcuts-test.rkt
default-recommendations/class-shortcuts-test.rkt
default-recommendations/comparison-shortcuts-test.rkt
default-recommendations/conditional-shortcuts-test.rkt
default-recommendations/contract-shortcuts-test.rkt
default-recommendations/definition-shortcuts-test.rkt
default-recommendations/file-io-suggestions-test.rkt
default-recommendations/for-loop-shortcuts-test.rkt
default-recommendations/function-definition-shortcuts-test.rkt
default-recommendations/gap-preservation-test.rkt
default-recommendations/hash-shortcuts-test.rkt
default-recommendations/let-binding-suggestions-comment-test.rkt
default-recommendations/let-binding-suggestions-test.rkt
default-recommendations/list-shortcuts-test.rkt
default-recommendations/match-shortcuts-test.rkt
default-recommendations/require-and-provide-suggestions-test.rkt
default-recommendations/shadowed-output-test.rkt
default-recommendations/string-shortcuts-test.rkt
default-recommendations/syntax-parse-shortcuts-test.rkt
default-recommendations/syntax-shortcuts-test.rkt
default-recommendations/unused-binding-suggestions-test.rkt
main.scrbl
test.rkt
test/explicit-require-no-auto-test.rkt

This makes it much more obvious which tests check that Resyntax *does* refactor something and which tests check that Resyntax *doesn't* refactor something.

Split new `no-change-test:` statement out of `test:`

---

base.rkt
private/syntax-replacement.rkt

"Universal Tagged Syntax" (UTS) is what I'm calling my approach to getting `syntax-replacement-render` to work on non-s-expression languages. Details TBD.

Add scaffolding for UTS replacements

---

test.rkt
test/private/grammar.rkt
test/private/tokenizer.rkt
test/testing-lang-test.rkt

Add prefixed code blocks to `#lang resyntax/test`

---

main.rkt

This should fix problems where bugs in the initial source analysis pass cause an entire Autofixer run to fail, as seen [here](https://github.com/racket/drracket/actions/runs/17703709869/job/50312526478).

Be more fault-tolerant during analysis
